// ── パスワード設定 ──────────────────────────────────────────
// ここを変更するとパスワードが変わります
const APP_PASSWORD = 'ubugoe2026';

// ── ロードマップ（制度・申請） ──────────────────────────────

const PHASES = [
  {
    id: 'early',
    name: '妊娠初期',
    period: '〜15週',
    icon: '🌱',
    color: '#86efac',
    activeText: '#166534',
    lightColor: '#f0fdf4',
    todos: [
      {
        title: '妊娠届を提出・母子手帳を受け取る',
        where: '区役所・区民事務所',
        deadline: 'なるべく早めに',
        url: 'https://www.city.katsushika.lg.jp/kenkou/1000050/1001803/1014924.html',
      },
      {
        title: 'ゆりかご面接を予約・受ける',
        where: '各健康センター',
        deadline: 'なるべく早めに',
        url: 'https://www.city.katsushika.lg.jp/kenkou/1000050/1001803/1014924.html',
      },
      {
        title: 'マタニティパスを申請（交通費6,000円分）',
        where: '母子手帳交付時に同時申請',
        deadline: '母子手帳受け取り時',
        url: 'https://www.city.katsushika.lg.jp/kenkou/1000050/1001803/1015907.html',
      },
      {
        title: '妊婦健康診査受診票を受け取る（14回分）',
        where: '母子手帳交付時',
        deadline: '母子手帳受け取り時',
        url: 'https://www.city.katsushika.lg.jp/kenkou/1000050/1001803/1002072.html',
      },
    ],
    benefits: [
      {
        name: '妊婦支援給付金',
        amount: 50000,
        tag: '現金',
        note: 'ゆりかご面接後に振込（葛飾区）',
        url: 'https://www.city.katsushika.lg.jp/kenkou/1000050/1001803/1014924.html',
      },
      {
        name: '妊娠子育て応援券',
        amount: 10000,
        tag: 'クーポン',
        note: 'ゆりかご面接後に配布（葛飾区）',
        url: 'https://www.city.katsushika.lg.jp/kenkou/1000050/1001803/1030902.html',
      },
      {
        name: 'マタニティパス',
        amount: 6000,
        tag: 'ICカード',
        note: '交通系ICカードへのチャージ（葛飾区）',
        url: 'https://www.city.katsushika.lg.jp/kenkou/1000050/1001803/1015907.html',
      },
      {
        name: '妊婦健診費用補助',
        amount: null,
        tag: '補助',
        note: '14回分の受診票。費用の一部を区が負担',
        url: 'https://www.city.katsushika.lg.jp/kenkou/1000050/1001803/1002072.html',
      },
    ],
    cashTotal: 66000,
  },
  {
    id: 'mid',
    name: '妊娠中期',
    period: '16〜27週',
    icon: '🌸',
    color: '#f9a8d4',
    activeText: '#831843',
    lightColor: '#fdf2f8',
    todos: [
      {
        title: '出産育児一時金の申請方式を産院に確認',
        where: '出産予定の医療機関',
        deadline: '早めに確認',
        url: 'https://www.city.katsushika.lg.jp/kurashi/1000049/1001690/1001740.html',
      },
      {
        title: '職場へ産休・育休の意向を伝える',
        where: '勤務先',
        deadline: '遅くとも28週頃まで',
        url: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000130583.html',
      },
      {
        title: '妊婦健診を継続受診',
        where: '産院',
        deadline: '定期的に',
        url: 'https://www.city.katsushika.lg.jp/kenkou/1000050/1001803/1002072.html',
      },
    ],
    benefits: [
      {
        name: '妊婦健診費用補助（継続）',
        amount: null,
        tag: '補助',
        note: '引き続き受診票を使用（葛飾区）',
        url: 'https://www.city.katsushika.lg.jp/kenkou/1000050/1001803/1002072.html',
      },
    ],
    cashTotal: 0,
  },
  {
    id: 'late',
    name: '妊娠後期',
    period: '28〜36週',
    icon: '🤰',
    color: '#c4b5fd',
    activeText: '#4c1d95',
    lightColor: '#f5f3ff',
    todos: [
      {
        title: '産休を開始（産前6週前〜任意）',
        where: '勤務先',
        deadline: '出産予定日の42日前〜',
        url: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000130583.html',
      },
      {
        title: '育児休業を申請（勤務先）',
        where: '勤務先',
        deadline: '育休開始1ヶ月前まで',
        url: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000130583.html',
      },
      {
        title: '出産育児一時金 受取代理制度を申請（希望時）',
        where: '区役所 国民健康保険・年金課',
        deadline: '出産予定日の2ヶ月前〜',
        url: 'https://www.city.katsushika.lg.jp/kurashi/1000049/1001690/1001740.html',
      },
      {
        title: '出産手当金の申請準備（会社員）',
        where: '勤務先の健康保険組合',
        deadline: '産後に申請',
        url: 'https://www.mhlw.go.jp/bunya/iryouhoken/iryouhoken13/index.html',
      },
    ],
    benefits: [],
    cashTotal: 0,
  },
  {
    id: 'birth',
    name: '出産',
    period: '37週〜',
    icon: '👶',
    color: '#fde68a',
    activeText: '#78350f',
    lightColor: '#fffbeb',
    todos: [
      {
        title: '出生届を提出',
        where: '区役所・区民事務所',
        deadline: '出生から14日以内（必須）',
        url: 'https://www.city.katsushika.lg.jp/kurashi/1000049/1001693/',
      },
      {
        title: '出産育児一時金を申請（直接支払制度以外の場合）',
        where: '区役所 国民健康保険・年金課',
        deadline: '出産から2年以内',
        url: 'https://www.city.katsushika.lg.jp/kurashi/1000049/1001690/1001740.html',
      },
      {
        title: '高額療養費を申請（帝王切開等）',
        where: '区役所 国民健康保険・年金課',
        deadline: '診療翌月〜2年以内',
        url: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/iryouhoken/juuyou/kougakuiryou/index.html',
      },
    ],
    benefits: [
      {
        name: '出産育児一時金',
        amount: 500000,
        tag: '現金',
        note: '国の制度。直接支払制度で医療機関へ直接支給が一般的',
        url: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kodomo/kodomo_kosodate/boshi-hoken/sanka-ichiji.html',
      },
      {
        name: '高額療養費',
        amount: null,
        tag: '還付',
        note: '帝王切開等の場合。所得に応じて自己負担上限あり',
        url: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/iryouhoken/juuyou/kougakuiryou/index.html',
      },
    ],
    cashTotal: 500000,
  },
  {
    id: 'postnatal',
    name: '産後',
    period: '〜生後4ヶ月',
    icon: '🍼',
    color: '#6ee7b7',
    activeText: '#064e3b',
    lightColor: '#f0fdf4',
    todos: [
      {
        title: 'こんにちは赤ちゃん訪問を受ける',
        where: '自宅（訪問）',
        deadline: '生後4ヶ月まで',
        url: 'https://www.city.katsushika.lg.jp/kenkou/1000050/1001803/',
      },
      {
        title: '児童手当を申請',
        where: '区役所 子育て応援課 / マイナポータル',
        deadline: '出生月末まで（月末以降は15日以内）',
        url: 'https://www.city.katsushika.lg.jp/kosodate/1000056/1002336/1002411.html',
      },
      {
        title: 'かつしか出産応援給付金を申請',
        where: '子育て応援課（児童手当と同時申請可）',
        deadline: '出生から1年以内',
        url: 'https://www.city.katsushika.lg.jp/kenkou/1000050/1001803/1031538.html',
      },
      {
        title: '子育て応援ギフトを申請',
        where: 'こんにちは赤ちゃん訪問後にオンライン申請',
        deadline: '生後4ヶ月まで',
        url: 'https://www.city.katsushika.lg.jp/kenkou/1000050/1001803/1030902.html',
      },
      {
        title: '赤ちゃんファースト（東京都）を申請',
        where: '専用ウェブサイト',
        deadline: '都の案内に従う',
        url: 'https://www.fukushi.metro.tokyo.lg.jp/kodomo/shussan/tokyo_shussankosodateouen',
      },
      {
        title: '産後ケアサービスを予約（希望時）',
        where: '青戸保健センター 03-3602-1284',
        deadline: '産後1年以内',
        url: 'https://www.city.katsushika.lg.jp/kenkou/1000050/1001803/1030308/1020863.html',
      },
    ],
    benefits: [
      {
        name: 'かつしか出産応援給付金',
        amount: 50000,
        tag: '現金',
        note: '葛飾区独自。児童1人あたり',
        url: 'https://www.city.katsushika.lg.jp/kenkou/1000050/1001803/1031538.html',
      },
      {
        name: '子育て応援ギフト',
        amount: 100000,
        tag: 'クーポン',
        note: '国の交付金事業。商品カタログから選択',
        url: 'https://www.city.katsushika.lg.jp/kenkou/1000050/1001803/1030902.html',
      },
      {
        name: '赤ちゃんファースト（東京都）',
        amount: 100000,
        tag: 'ポイント',
        note: '東京都独自。商品カタログから選択',
        url: 'https://www.fukushi.metro.tokyo.lg.jp/kodomo/shussan/tokyo_shussankosodateouen',
      },
      {
        name: '産後ケアサービス',
        amount: null,
        tag: 'サービス',
        note: '基本無料。宿泊最大7日、通所・訪問最大7回',
        url: 'https://www.city.katsushika.lg.jp/kenkou/1000050/1001803/1030308/1020863.html',
      },
    ],
    cashTotal: 250000,
  },
  {
    id: 'childcare',
    name: '育児期',
    period: '継続',
    icon: '👨‍👩‍👧',
    color: '#93c5fd',
    activeText: '#1e3a5f',
    lightColor: '#eff6ff',
    todos: [
      {
        title: '育児休業給付金を申請（会社員）',
        where: 'ハローワーク（勤務先が代行）',
        deadline: '育休開始後',
        url: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000160564.html',
      },
      {
        title: '出産手当金を申請（会社員）',
        where: '勤務先の健康保険組合',
        deadline: '産後56日以降',
        url: 'https://www.mhlw.go.jp/bunya/iryouhoken/iryouhoken13/index.html',
      },
      {
        title: '保育園申込（希望時）',
        where: '区役所 保育課 03-5654-8278',
        deadline: '年度により異なる（要確認）',
        url: 'https://www.city.katsushika.lg.jp/kosodate/1000056/1002333/1036720.html',
      },
      {
        title: '医療費控除の確定申告',
        where: '税務署 / e-Tax',
        deadline: '翌年2〜3月',
        url: 'https://www.nta.go.jp/taxes/shiraberu/taxanswer/shotoku/1120.htm',
      },
    ],
    benefits: [
      {
        name: '児童手当',
        amount: null,
        tag: '毎月',
        note: '3歳未満：月1.5万円 / 3歳以上：月1万円〜',
        url: 'https://www.city.katsushika.lg.jp/kosodate/1000056/1002336/1002411.html',
      },
      {
        name: '育児休業給付金',
        amount: null,
        tag: '変動',
        note: '給与の67%（最初の180日）→50%（以降）。雇用保険から',
        url: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000160564.html',
      },
      {
        name: '出産手当金',
        amount: null,
        tag: '変動',
        note: '産前42日〜産後56日。標準報酬日額の2/3',
        url: 'https://www.mhlw.go.jp/bunya/iryouhoken/iryouhoken13/index.html',
      },
    ],
    cashTotal: 0,
  },
];


// ── 妊娠カレンダー ──────────────────────────────────────────

const CALENDAR_WEEKS = [
  {
    week: 4,
    trimester: 'first',
    label: '4週',
    babySize: 'ケシ粒（約2mm）',
    babyEmoji: '🌰',
    babyDev: '受精卵が子宮に着床。胎嚢が超音波で見える頃',
    momBody: '生理が来ない。妊娠検査薬が陽性に',
    attention: '飲酒・喫煙を避ける。葉酸サプリを摂取',
    medical: '産婦人科を受診し妊娠を確認',
  },
  {
    week: 6,
    trimester: 'first',
    label: '6週',
    babySize: 'ブルーベリー（約6mm）',
    babyEmoji: '🫐',
    babyDev: '心拍が確認できる。手足の芽が出始める',
    momBody: 'つわりが始まる。眠気・頻尿が増える',
    attention: 'つわりはいつでも来る。水分補給を忘れずに',
    medical: '心拍確認。妊娠確定',
  },
  {
    week: 8,
    trimester: 'first',
    label: '8週',
    babySize: 'ラズベリー（約16mm）',
    babyEmoji: '🍓',
    babyDev: '顔の形・指ができてくる。動き始める',
    momBody: 'つわりがピーク。胸が張る',
    attention: '無理をしない。休める環境を整える',
    medical: '経過観察・超音波検査',
  },
  {
    week: 10,
    trimester: 'first',
    label: '10週',
    babySize: 'イチゴ（約3cm）',
    babyEmoji: '🍓',
    babyDev: '「胎児」と呼ばれる時期に。主要な器官がほぼ完成',
    momBody: 'つわりはまだ続く。子宮が大きくなり下腹部が張ってくる',
    attention: '転倒に注意。お腹を圧迫しない服装に',
    medical: 'NIPT（非侵襲的出生前検査）は10週〜受検可能',
  },
  {
    week: 12,
    trimester: 'first',
    label: '12週',
    babySize: 'ライム（約5〜6cm）',
    babyEmoji: '🍋',
    babyDev: '手足をよく動かす。外性器が発達し始める',
    momBody: '安定期が近づく。つわりが和らぐ人も',
    attention: '母子手帳をもらう頃。妊娠届を出して受け取ろう',
    medical: 'NT（首の厚さ）スクリーニング。初期胎児ドック',
  },
  {
    week: 14,
    trimester: 'first',
    label: '14週',
    babySize: 'レモン（約8〜9cm）',
    babyEmoji: '🍋',
    babyDev: '胎盤が完成。ほぼ完成した人間の形に',
    momBody: 'つわりが落ち着く人が多い。食欲が戻り始める',
    attention: '体重管理を意識しはじめる（増えすぎ・少なすぎに注意）',
    medical: '安定期目前。この頃から動きやすくなる',
  },
  {
    week: 16,
    trimester: 'second',
    label: '16週',
    babySize: 'アボカド（約12cm）',
    babyEmoji: '🥑',
    babyDev: '頭皮に髪の毛が生え始める。表情筋が動く',
    momBody: '経産婦はこの頃から胎動を感じる人も',
    attention: 'マタニティウェア・腹帯を準備し始める',
    medical: '性別がわかる産院も（まだ難しい場合が多い）',
  },
  {
    week: 18,
    trimester: 'second',
    label: '18週',
    babySize: 'サツマイモ（約14cm）',
    babyEmoji: '🍠',
    babyDev: '体が丸みを帯びてくる。聴覚が発達し音を感じる',
    momBody: '初産婦もぼんやり胎動を感じ始める（ポコポコ・クルクル）',
    attention: '声かけ・音楽を聞かせるコミュニケーションを',
    medical: '性別がわかることが多い時期',
  },
  {
    week: 20,
    trimester: 'second',
    label: '20週',
    babySize: 'バナナ（約25cm）',
    babyEmoji: '🍌',
    babyDev: '全身に産毛（胎毛）が生える。寝たり起きたりリズムが生まれる',
    momBody: 'お腹がはっきり大きくなる。腰痛が出始める人も',
    attention: '妊娠中期の山場。無理をせず体を動かすのは良い',
    medical: '中期詳細超音波（胎児の臓器・形態チェック）',
  },
  {
    week: 22,
    trimester: 'second',
    label: '22週',
    babySize: 'パパイヤ（約27cm）',
    babyEmoji: '🫑',
    babyDev: '指紋ができる。肺が急速に発達',
    momBody: '胎動がはっきりわかる。パパも触れてわかることも',
    attention: '早産のリスクに注意。無理な運動を避ける',
    medical: '22週未満は人工妊娠中絶が可能な最終時期',
  },
  {
    week: 24,
    trimester: 'second',
    label: '24週',
    babySize: 'コーン（約30cm）',
    babyEmoji: '🌽',
    babyDev: '体に皮下脂肪がつき始める。まぶたが開閉できる',
    momBody: 'お腹の重みで姿勢が変わる。こむら返りが起きやすい',
    attention: '妊娠糖尿病スクリーニング検査の時期',
    medical: '50g グルコースチャレンジテスト（GCT）',
  },
  {
    week: 28,
    trimester: 'third',
    label: '28週',
    babySize: '茄子（約37cm）',
    babyEmoji: '🍆',
    babyDev: '体重が急増し始める。脳が発達し、音・光に反応',
    momBody: '後期突入。貧血・むくみが出やすい',
    attention: '鉄分をしっかり摂る。入院準備を考え始める',
    medical: '後期血液検査（貧血・感染症チェック）',
  },
  {
    week: 30,
    trimester: 'third',
    label: '30週',
    babySize: 'キャベツ（約40cm）',
    babyEmoji: '🥬',
    babyDev: '骨が硬くなる。羊水の中で練習呼吸をする',
    momBody: '胃が圧迫され食欲が落ちる人も。頻尿が再び増える',
    attention: '逆子の確認時期。ほとんどは自然に直る',
    medical: '逆子チェック（胎位確認）',
  },
  {
    week: 32,
    trimester: 'third',
    label: '32週',
    babySize: 'スイカ（小）（約42cm）',
    babyEmoji: '🍉',
    babyDev: '爪・まつ毛が生える。肺が出生後に備えて成熟',
    momBody: '動くのが辛くなる。動悸・息切れが出ることも',
    attention: '出産に向けた準備（入院バッグ・陣痛アプリなど）を始める',
    medical: '胎児の成長を毎回チェック。逆子は32週でほぼ確定',
  },
  {
    week: 35,
    trimester: 'third',
    label: '35〜36週',
    babySize: 'メロン（約46cm）',
    babyEmoji: '🍈',
    babyDev: 'ほぼ出産時と同じ大きさ。内臓が完成に近づく',
    momBody: '赤ちゃんが下がってきてお腹が軽くなる人も',
    attention: '産前休暇（産前42日前）。入院準備を完成させる',
    medical: 'GBSスクリーニング。毎週健診に変わる産院も',
  },
  {
    week: 37,
    trimester: 'term',
    label: '37週（正期産）',
    babySize: 'スイカ（約48cm）',
    babyEmoji: '🍉',
    babyDev: '正期産。いつ産まれてもOKな成熟度に',
    momBody: '前駆陣痛が来ることも。おしるし・破水に注意',
    attention: '陣痛・破水のサインを把握する。産院の連絡先を確認',
    medical: '毎週健診。いつでも入院できる準備を',
  },
  {
    week: 40,
    trimester: 'term',
    label: '40週（予定日）',
    babySize: 'スイカ（約50cm）',
    babyEmoji: '👶',
    babyDev: 'ついに予定日！でも±2週は正常範囲',
    momBody: '陣痛が来るのを待つ。緊張と楽しみが混じる',
    attention: '陣痛間隔をアプリで計る。落ち着いて対処を',
    medical: '陣痛が規則的に（初産：10分間隔、経産：15分間隔）になったら入院',
  },
];

// ── 情報タブ：ニュース・YouTube ──────────────────────────

// CORS プロキシを順に試す（一方がブロックされても代替で動く）
const CORS_PROXIES = [
  url => `https://corsproxy.io/?${encodeURIComponent(url)}`,
  url => `https://api.allorigins.win/raw?url=${encodeURIComponent(url)}`,
];

const NEWS_SOURCES = [
  { label: '妊娠・出産ニュース', url: 'https://news.google.com/rss/search?q=%E5%A6%8A%E5%A8%A0+%E5%87%BA%E7%94%A3+%E8%82%B2%E5%85%90&hl=ja&gl=JP&ceid=JP:ja' },
  { label: '子育て・育児ニュース', url: 'https://news.google.com/rss/search?q=%E5%AD%90%E8%82%B2%E3%81%A6+%E8%B5%A4%E3%81%A1%E3%82%83%E3%82%93+%E8%82%B2%E5%85%90&hl=ja&gl=JP&ceid=JP:ja' },
];

const YT_CHANNELS = [
  { name: '助産師HISAKO', id: 'UCgLt6RS5cHmL6i15sbu2kGw' },
  { name: '助産師はるか 安産塾', id: 'UCFQ-kjcWEmRTF0rkzevxSDw' },
  { name: 'ホッとできる！産婦人科', id: 'UCladKIzy02qqzmktiZmWOAA' },
];

const TRIMESTER_INFO = {
  first:  { label: '妊娠初期',  weeks: '4〜14週',  color: '#bbf7d0', text: '#166534' },
  second: { label: '妊娠中期',  weeks: '15〜27週', color: '#fbcfe8', text: '#831843' },
  third:  { label: '妊娠後期',  weeks: '28〜36週', color: '#ddd6fe', text: '#4c1d95' },
  term:   { label: '出産期',    weeks: '37週〜',   color: '#fef08a', text: '#78350f' },
};
